name = "founder-vent"
compatibility_date = "2026-08-19"
main = "worker/index.js"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "founder-vent-db"
database_id = "424da0fa-4126-45c4-a207-d00434279196"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "founder-vent-images"
