name = "landingpro-admin"
main = "worker/index.js"
compatibility_date = "2026-08-21"

[assets]
directory = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "landingpro-core"
database_id = "392fc9b6-7c42-4cce-a05c-cdabf23d7a1d"

